server:
  port: 8083

spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 47.115.53.135:9300
  jackson:
    default-property-inclusion: non_null #不包含为null的字段
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10 #拉取微服务注册表时间
  instance:
    lease-expiration-duration-in-seconds: 15 #过期时间
    lease-renewal-interval-in-seconds: 5 #心跳时间