server:
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///leyou?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  rabbitmq:
    host: 192.168.174.38
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #心跳时间
    lease-expiration-duration-in-seconds: 15 #过期时间

mybatis:
  type-aliases-package: com.leyou.item.pojo #别名扫描
